### ISSUE TITLE
getting only zeroes

### ISSUE THREAD

**Issue by alponet** [algomusic/Mozzi_MPU6050#1]
Hello and thanks for sharing your code.
I'm also trying to make the MPU6050 work with Mozzi, but I'm only getting zeroes, also with your implementation. Any idea why that could happen? How do you wire things up? In the MPU6050 documentation, pins A5 and A4 are mentioned, which are not available on the Mozzi.
Cheers and thanks for your help!

**Comment by algomusic** [comment]
Wiring should be pretty standard for I2C - power, ground, SCL and SDA. I found that I got zeros, like you report, at times and needed to repower the board to 'reset' things.
